### ISSUE TITLE
Ajouter shapefiles avec zones de pêche

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/PecheFantome#7]
https://ouvert.canada.ca/data/fr/dataset/59af1c96-fc8f-4fa0-b398-d65e953eadaa

On veut les zones de peche au crabe et homard

**Comment by Ddoiron-cidco** [comment]
implémenter mais du a des raison de sécurité le fichier html ne peut télécharger le fichier en local donc il faut que le tout soit sur un serveur html

**Comment by Ddoiron-cidco** [comment]
il est a noter que le fichier shp contien toute les zones de peches donc il est pas possible de sélectionner q'une seulle zone. pour cela il faudrais un fichier shp pour chaque zone.

**Comment by glabmoris** [comment]
C'est parfait pour l'instant
